title: Kyungchan Lim
include: ./lim.png
description: Ph.D. Student @ EECS UTK 
# description: 339 Min H. Kao Bldg 
# description: klim7@utk.edu
# show_downloads: true
theme: jekyll-theme-minimal
# theme: jekyll-theme-basic
# theme: jekyll-theme-basically-basic
# theme: academic-jekyll-theme
